### ISSUE TITLE
General user account management

### ISSUE THREAD

**Issue by KowalskiPiotr98** [rinkudesu/rinkudesu-identity#6]
This is a general tracking issue for all basic functinality. This might stay as is or be converted into a project later on if it's worth it.

Users should be able to:
- [x] change password,
- [x] #23,
- [x] #26,
- [x] #28,
- [x] #29,
- [x] #30,
- [x] by the end, make sure the ordering of this view is at least somewhat logical,
- [x] add missing documentation.

Tasks to do for pretty much everything above:
- [x] Some selenium tests should be added to all this including fixing `docker-compose` to use this service.

**Comment by KowalskiPiotr98** [comment]
I'm just gonna go through this list here and mark things as completed, as some of them will just happen together, so making a project seems more difficult than this.

**Comment by KowalskiPiotr98** [comment]
Since the "log out everywhere" functionality requires some changes to the Redis session store, I'll do that one separately.

**Comment by KowalskiPiotr98** [comment]
Yeah, this won't work, will need to split this.

**Comment by KowalskiPiotr98** [comment]
Closing as completed.
